[package]
name = "hadron_sclang_fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "*"
hadron_sclang = "0.1.0-alpha.1"

